### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jpmec**
Added files for basic framework to allow user to use different 'tools' and 'selectors' to create commands that modify the image.  Still rough, but gives an idea of the interaction between objects.

### CODE REVIEW

**Comment by onezeno** [comment]
Holy shit 71 files! Well, I checked it out. I'll start looking at it. Why did you commit to master instead of develop?

**Comment by onezeno** [comment]
Does this build for you?

**Comment by jpmec** [comment]
Dang, sorry, I meant to make the pull request to develop :-(  so sorry

**Comment by jpmec** [comment]
It does build for me, I probably screwed something up in the commit

**Comment by onezeno** [comment]
Well, I fixed two errors:
#include "Imagepoint2d.h" ... had to rename this to imagepoint2d.h in several places
Had to add Config += C++11 to the .pro file for std: shared_ptr
Now I have 15 errors left. The first comes from line 19 of selection.h.  It says:
/home/james/Photobalm/Photobalm/src/selection.h:19: error: expected nested-name-specifier before 'Iterator'

**Comment by onezeno** [comment]
What compiler are you using? I'm surprised if was caps-agnostic to file name, or didn't require the c++11 argument.

**Comment by jpmec** [comment]
I'm pretty sure I was using the microsoft toolchain, I've reforked and am going to try and get qt back up and running.  I didn't delete my old local repo, so i should be able to get it back up and running pretty quick

**Comment by jpmec** [comment]
are you using gcc? I can try to set that up

**Comment by jpmec** [comment]
K, back up and running.  I'm using the kit for Desktop Qt 5.4.0 MSVC2010 OpenGL 32bit and this builds and runs.

**Pull request merged**
